### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by stefangal** [stefangal/Tictactoe#1]
- [x] 1 player game skelet using OOP
- [x] CLI visualisation done
- [x] OOP module to check winner
- [x] For each round the game should return i.e. "game": "O---X----" and "player":"O" output to API
- [x] Prepare API interface to game.py
- [x] Prepare interactive play
- [x] Add check to avoid moves which were already made
- [x] Play again added
